[package]
name = "pandedup"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
either = "1.17.0"
gxhash = "3.5.0"
num_cpus = "1.17.0"
# ragc-core = "0.1.1"
# ragc-core.path = "../forks/ragc/ragc-core"
ragc-core.git = "https://github.com/ragnargrootkoerkamp/ragc"
rand = "0.10.2"
seq-hash = "0.2.0"
simd-minimizers = "3.0.0"
zstd = "0.13.3"


[patch.crates-io]
# seq-hash = { path = "../seq-hash" }
seq-hash.git = "https://github.com/rust-seq/seq-hash"
